### ISSUE TITLE
Incorrect calculation of error percentage (%) alarms

### ISSUE THREAD

**Issue by svennjegac** [aws-samples/amazon-dynamodb-monitoring#2]
Hello,

I am using this repo as a reference for creating DynamoDB alarms.

I found 4 alarms, which I think are not implemented correctly.
Those alarms are calculating percentage (%) of errors and if error percentage is over threshold, alarm will be raised.

Calculation (based on the first alarm in the PR - system errors):

m1 = number_of_errors
m2 = number_of_consumed_read_capacity_units
m3 = number_of_consumed_write_capacity_units

expression = m1 / (m2 + m3)

From this, it is clear that 0 <= expression <= 1.0, but this is compared to threshold = 2.0%.

Please if you can reply and confirm that this is a bug (and merge this PR).
Or if I am not understanding this correctly, please explain what am I missing.

PR with a fix: https://github.com/aws-samples/amazon-dynamodb-monitoring/pull/1

**Comment by svennjegac** [comment]
cc @ctindel

**Comment by ctindel** [comment]
@svennjegac I am no longer at AWS but have forwarded this on to the team who is still there

**Comment by svennjegac** [comment]
> @svennjegac I am no longer at AWS but have forwarded this on to the team who is still there

Really appreciate your effort, thanks!

**Comment by tebanieo** [comment]
Thanks for reporting and solving the bug, I have merged the changes. in #1
